version: '3.9'
services:
  arangodb:
    # for some reason, version 3.9 does not work
    image: arangodb:3.8
    ports:
      - '8529:8529'
    environment:
      # - ARANGO_RANDOM_ROOT_PASSWORD=1
      - ARANGO_ROOT_PASSWORD=fuckgfw
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:8529
      # - --http.trusted-origin=* # this will allow client JavaScript access
  web:
    build:
      context: "./"
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - VERCEL_URL=reink.app
volumes:
  arangodb_data_container:
  arangodb_apps_data_container:

