# fly.toml app configuration file generated for reink-nvrk on 2024-10-19T16:55:59+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reink-nvrk'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
